name: "Validate Infrastructure Variables"

on:
  workflow_call:
    outputs:
      region:
        value: ${{ jobs.validate.outputs.region }}
      destroy_infra:
        value: ${{ jobs.validate.outputs.destroy_infra }}
      queue_name:
        value: ${{ jobs.validate.outputs.queue_name }}
      dlq_name:
        value: ${{ jobs.validate.outputs.dlq_name }}
      topic_name:
        value: ${{ jobs.validate.outputs.topic_name }}

jobs:
  validate:
    runs-on: ubuntu-22.04
    outputs:
      region: ${{ steps.vars.outputs.region }}
      destroy_infra: ${{ steps.vars.outputs.destroy_infra }}
      queue_name: ${{ steps.vars.outputs.queue_name }}
      dlq_name: ${{ steps.vars.outputs.dlq_name }}
      topic_name: ${{ steps.vars.outputs.topic_name }}

    steps:
      - uses: actions/checkout@v2
      
      - id: vars
        name: Read Variables
        run: |
          echo "region=$(grep 'region' infra/terraform.tfvars | cut -d'"' -f2)" >> $GITHUB_OUTPUT
          echo "destroy_infra=$(grep 'destroy_infra' infra/terraform.tfvars | cut -d'=' -f2 | tr -d '[:space:]')" >> $GITHUB_OUTPUT
          echo "queue_name=$(grep 'queue_name' infra/terraform.tfvars | cut -d'"' -f2)" >> $GITHUB_OUTPUT
          echo "dlq_name=$(grep 'deadletter_name' infra/terraform.tfvars | cut -d'"' -f2)" >> $GITHUB_OUTPUT
          echo "topic_name=$(grep 'topic_name' infra/terraform.tfvars | cut -d'"' -f2)" >> $GITHUB_OUTPUT
