name: "Notify PR"

on:
  workflow_call:
    inputs:
      queue_name:
        required: true
        type: string
      dlq_name:
        required: true
        type: string
      topic_name:
        required: true
        type: string
      destroy_infra:
        required: true
        type: string

permissions:
  pull-requests: write

jobs:
  notify:
    runs-on: ubuntu-22.04
    steps:
      - name: Add comment to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const action = "${{ inputs.destroy_infra }}" === "true" ? "destruíd" : "criad";
            const msg = [
              `Queue ${{ inputs.queue_name }} foi ${action}a com sucesso!`,
              `Deadletter Queue ${{ inputs.dlq_name }} foi ${action}a com sucesso!`,
              `Topic ${{ inputs.topic_name }} foi ${action}o com sucesso!`
            ].join('\n');
            
            github.rest.issues.createComment({
              owner: context.repo.owner,
              issue_number: context.issue.number,
              repo: context.repo.repo,
              body: msg
            });
