name: Create Queue and Notification Service

on:
  pull_request:
    types: opened
    branches:
      - main
      - feature/*

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install figlet
        run: npm install -g figlet-cli

      - name: Verify tfvars files
        run: |
          if [ ! -f infra/terraform.tfvars ]; then
            figlet "Error: Missing terraform.tfvars"
            exit 1
          fi

      - name: Get Region from tfvars
        run: |
          export REGION=$(grep 'region' infra/terraform.tfvars | cut -d'"' -f2)
          echo "Region: $REGION"
          echo "REGION=$REGION" >> $GITHUB_ENV

      - name: Set up AWS Cli
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Get Description from pull request
        run: |
          export DESCRIPTION=$(echo "${{ github.event.pull_request.body }}")
          echo "Description: $DESCRIPTION"
          echo "DESCRIPTION=$DESCRIPTION" >> $GITHUB_ENV

      - name: Get Destroy infra from tfvars
        run: |
          export DESTROY_INFRA=$(cat infra/terraform.tfvars | grep destroy_infra | cut -d'=' -f2 | tr -d '[:space:]')
          echo "Destroy Infra: $DESTROY_INFRA"
          echo "DESTROY_INFRA=$DESTROY_INFRA" >> $GITHUB_ENV

      - name: Destroy infra if variable is set
        if: ${{ env.DESTROY_INFRA == 'true' }}
        run: |
          cd infra
          terraform init || (figlet "Error: Terraform Init Failed" && exit 1)
          terraform plan -destroy -out=tfplan || (figlet "Error: Terraform Plan Failed" && exit 1)
          terraform apply tfplan || (figlet "Error: Terraform Apply Failed" && exit 1)

      - name: Get Queue Name from tfvars
        run: |
          export QUEUE_NAME=$(grep 'queue_name' infra/terraform.tfvars | cut -d'"' -f2)
          echo "Queue Name: $QUEUE_NAME"
          echo "QUEUE_NAME=$QUEUE_NAME" >> $GITHUB_ENV
      
      - name: Get deadletter Queue Name from tfvars
        run: |
          export DEADLETTER_QUEUE_NAME=$(grep 'deadletter_name' infra/terraform.tfvars | cut -d'"' -f2)
          echo "Deadletter Queue Name: $DEADLETTER_QUEUE_NAME"
          echo "DEADLETTER_QUEUE_NAME=$DEADLETTER_QUEUE_NAME" >> $GITHUB_ENV

      - name: Get Topic Name from tfvars
        run: |
          export TOPIC_NAME=$(grep 'topic_name' infra/terraform.tfvars | cut -d'"' -f2)
          echo "Topic Name: $TOPIC_NAME"
          echo "TOPIC_NAME=$TOPIC_NAME" >> $GITHUB_ENV

      - name: Create Infra if destroy variable is not set
        if: ${{ env.DESTROY_INFRA != 'true' }}
        run: |
          cd infra
          terraform init || (figlet "Error: Terraform Init Failed" && exit 1)
          terraform plan -out=tfplan || (figlet "Error: Terraform Plan Failed" && exit 1)
          terraform apply tfplan || (figlet "Error: Terraform Apply Failed" && exit 1)

      - name: Set PR msg
        run: |
          echo "MSG=Queue ${QUEUE_NAME} foi ${{ env.DESTROY_INFRA == 'true' && 'destruída' || 'criada' }} com sucesso!" >> $GITHUB_ENV
          echo "MSG=${MSG}$(echo -e '\n')Deadletter Queue ${DEADLETTER_QUEUE_NAME} foi ${{ env.DESTROY_INFRA == 'true' && 'destruída' || 'criada' }} com sucesso!" >> $GITHUB_ENV
          echo "MSG=${MSG}$(echo -e '\n')Topic ${TOPIC_NAME} foi ${{ env.DESTROY_INFRA == 'true' && 'destruído' || 'criado' }} com sucesso!" >> $GITHUB_ENV

      - name: Add comment to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              issue_number: ${{ github.event.pull_request.number }},
              repo: context.repo.repo,
              body: `${{ env.MSG }}`
            })